/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author jhayber
 */
public class GUIInicio extends javax.swing.JFrame implements AView{

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuRegIngreso = new javax.swing.JMenuItem();
        mnuRegSalida = new javax.swing.JMenuItem();
        mnuRegMulta = new javax.swing.JMenuItem();
        mnuMapa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        mnuOpciones.setText("Opciones");

        mnuRegIngreso.setText("Registrar Ingreso");
        mnuRegIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegIngresoActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRegIngreso);

        mnuRegSalida.setText("Registrar Salida");
        mnuOpciones.add(mnuRegSalida);

        mnuRegMulta.setText("Registrar Multa");
        mnuOpciones.add(mnuRegMulta);

        jMenuBar2.add(mnuOpciones);

        mnuMapa.setText("Ver Mapa");
        jMenuBar2.add(mnuMapa);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegIngresoActionPerformed
        GUIBuscarVehPersona objIngreso = new GUIBuscarVehPersona();
        objIngreso.setMaximizable(true);
        dskEscritorio.add(objIngreso);
        try {
            objIngreso.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        objIngreso.show();
    }//GEN-LAST:event_mnuRegIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mnuMapa;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuRegIngreso;
    private javax.swing.JMenuItem mnuRegMulta;
    private javax.swing.JMenuItem mnuRegSalida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        
    }


}
