package presentacion;
import Utilidades.imgen_Escritorio;
import Utilidades.Utilidades;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import main.RunMVC;
import mvcf.AModel;
import mvcf.AView;
import negocio.GestorBahia;
import negocio.ReporteCongestion;
import negocio.conector;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class GUIInicio extends javax.swing.JFrame implements AView{

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
         this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/carro.png")).getImage());
         this.setTitle("APLICACION PARQUEADERO CDU UNICAUCA");
        Utilidades.mensajeExito("Bienvenido", "Inicio Exitoso");
        //dskEscritorio.setBorder(new imgen_Escritorio());
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuRegIngreso = new javax.swing.JMenuItem();
        mnuRegMulta = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dskEscritorio.setBackground(new java.awt.Color(12, 61, 135));

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        mnuOpciones.setText("Opciones");

        mnuRegIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_icon-icons.com_54424.png"))); // NOI18N
        mnuRegIngreso.setText("Buscar Conductor");
        mnuRegIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegIngresoActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRegIngreso);

        mnuRegMulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1477521607_halloween_outline-02_icon-icons.com_74588.png"))); // NOI18N
        mnuRegMulta.setText("Registrar Multa");
        mnuRegMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegMultaActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRegMulta);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/map_search_find_maps_10803.png"))); // NOI18N
        jMenuItem3.setText("Ver Mapa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuOpciones.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bar_chart_21471.png"))); // NOI18N
        jMenuItem4.setText("Reporte de Congestion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuOpciones.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_logout_door_1563.png"))); // NOI18N
        jMenuItem2.setText("Cerrar seccion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuOpciones.add(jMenuItem2);

        jMenuBar2.add(mnuOpciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegIngresoActionPerformed
        GUIBuscarVehPersona objIngreso = new GUIBuscarVehPersona();
        objIngreso.setMaximizable(true);
        dskEscritorio.add(objIngreso);
        try {
            objIngreso.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        objIngreso.show();
    }//GEN-LAST:event_mnuRegIngresoActionPerformed

    private void mnuRegMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegMultaActionPerformed
        GUIRegistroMulta objMultas = new GUIRegistroMulta();
        GUIInicio.dskEscritorio.add(objMultas);
        objMultas.toFront();
        objMultas.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegMultaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        setVisible(false);
        RunMVC objRun = new RunMVC();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         GUIMapaParqueadero mapa = null;
        try {
            mapa = new GUIMapaParqueadero();
        } catch (InterruptedException ex) {
            Logger.getLogger(GUIInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
         mapa.verMapa();
         mapa.setLocation(720, 0);
         mapa.setVisible(true);
   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                GestorBahia objParqueadero = new GestorBahia();
        ArrayList<ReporteCongestion> listaReportes = null;
        try {
            listaReportes = objParqueadero.reporteIngreso();
            if (!listaReportes.equals("No se encontro reportes.")) {
                conector con = new conector();
                Connection conn = con.getConecion();
                try {
                    JasperReport reporte;
                    //C:\Users\HP\Desktop\appProyectoFinal\appParqueaderoTulcan\src\Reporte\ReporteCongestion.jasper
                    String path = "C:\\Users\\HP\\Desktop\\appProyectoFinal\\appParqueaderoTulcan\\src\\Reporte\\ReporteCongestion.jasper";
                    reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Se carga el reporte de su localizacion
                    JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn); //Agregamos los parametros para llenar el reporte
                    JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reportes
                    viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Se declara con dispose_on_close para que no se cierre el programa cuando se cierre el reporte
                    viewer.setVisible(true); //Se vizualiza el reporte

                } catch (JRException ex) {
                    Logger.getLogger(GUIInicio.class.getName()).log(Level.SEVERE, null, ex);
                    Utilidades.mensajeError(ex.getMessage(), "Error");
                }
            } else {
                Utilidades.mensajeError("No existen datos", "Error");
            }
        } catch (Exception ex) {
            Utilidades.mensajeError(ex.getMessage(), "Error");
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuRegIngreso;
    private javax.swing.JMenuItem mnuRegMulta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        
    }


}
