package presentacion;

import Utilidades.Utilidades;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mvcf.AModel;
import mvcf.AView;

public class GUIInicio extends javax.swing.JFrame implements AView{

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
       
        Utilidades.mensajeExito("Bienvenido", "Inicio Exitoso");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuRegIngreso = new javax.swing.JMenuItem();
        mnuRegMulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dskEscritorio.setBackground(new java.awt.Color(12, 61, 135));

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        mnuOpciones.setText("Opciones");

        mnuRegIngreso.setText("Buscar Conductor");
        mnuRegIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegIngresoActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRegIngreso);

        mnuRegMulta.setText("Registrar Multa");
        mnuRegMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegMultaActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRegMulta);

        jMenuBar2.add(mnuOpciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegIngresoActionPerformed
        GUIBuscarVehPersona objIngreso = new GUIBuscarVehPersona();
        objIngreso.setMaximizable(true);
        dskEscritorio.add(objIngreso);
        try {
            objIngreso.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        objIngreso.show();
    }//GEN-LAST:event_mnuRegIngresoActionPerformed

    private void mnuRegMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegMultaActionPerformed
        GUIRegistroMulta objMultas = new GUIRegistroMulta();
        GUIInicio.dskEscritorio.add(objMultas);
        objMultas.toFront();
        objMultas.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegMultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuRegIngreso;
    private javax.swing.JMenuItem mnuRegMulta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        
    }


}
