/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import java.util.ArrayList;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author JUAN
 */
public class GUIMapaParqueadero extends javax.swing.JFrame implements AView{ 
   
    private String tipoEstado;
    
    private String accion;
    //estado 
    //    0=comienzo y no puede modificar los puestos 
    //    1=selecciono el estado entrada y solo puede seleccionar uno de los botones si esta disponible
    //    2=selecciono el estado salida y solo puede seleccionar una de los botones disponibles
    //    3=que ya se selcciono uno y no se puede poner otro solo si se desmarca
    private static int estado = 0;
    private ArrayList<javax.swing.JButton> listabt;
   
    public GUIMapaParqueadero() {
        initComponents();
        listabt=new ArrayList<javax.swing.JButton> ();
        btnguardar.setEnabled(false);
        //TODO aqui tenes que cargar los datos que si esten en el parqueadero
        //esto se hace cuando se comienza el progrma por eso se pone asi
        btnZonaD.setBackground(Color.WHITE);
        btnZonaD1.setBackground(Color.WHITE);
        btnZonaD2.setBackground(Color.WHITE);
        btnZonaD3.setBackground(Color.WHITE);
        btnZonaD4.setBackground(Color.WHITE);
        btnZonaD5.setBackground(Color.WHITE);
        btnZonaA.setBackground(Color.WHITE);
        btnZonaA1.setBackground(Color.WHITE);
        btnZonaA2.setBackground(Color.WHITE);
        btnZonaA3.setBackground(Color.WHITE);
        btnZonaA4.setBackground(Color.WHITE);
        btnZonaA5.setBackground(Color.WHITE);
        btnZonaC1.setBackground(Color.WHITE);
        btnZonaC2.setBackground(Color.WHITE);
        btnZonaC3.setBackground(Color.WHITE);
        btnZonaC4.setBackground(Color.WHITE);
        btnZonaC5.setBackground(Color.WHITE);
        btnZonaC6.setBackground(Color.WHITE);
        btnZonaC7.setBackground(Color.WHITE);
        btnZonaC8.setBackground(Color.WHITE);
        btnZonaC9.setBackground(Color.WHITE);
        btnZonaC10.setBackground(Color.WHITE);
        btnZonaC11.setBackground(Color.WHITE);
        btnZonaC12.setBackground(Color.WHITE);
        btnZonaB1.setBackground(Color.WHITE);
        btnZonaB2.setBackground(Color.WHITE);
        btnZonaB3.setBackground(Color.WHITE);
        btnZonaB4.setBackground(Color.WHITE);
        btnZonaB5.setBackground(Color.WHITE);
        btnZonaB6.setBackground(Color.WHITE);
        btnZonaB7.setBackground(Color.WHITE);
        btnZonaB8.setBackground(Color.WHITE);
        btnZonaB9.setBackground(Color.WHITE);
        btnZonaB10.setBackground(Color.WHITE);
        btnZonaB11.setBackground(Color.WHITE);
        btnZonaB12.setBackground(Color.WHITE);
        btnZonaB13.setBackground(Color.WHITE);
        btnZonaB14.setBackground(Color.WHITE);
        btnZonaB15.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLIbre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnZonaC1 = new javax.swing.JButton();
        btnZonaC2 = new javax.swing.JButton();
        btnZonaC3 = new javax.swing.JButton();
        btnZonaC4 = new javax.swing.JButton();
        btnZonaC5 = new javax.swing.JButton();
        btnZonaC6 = new javax.swing.JButton();
        btnZonaC7 = new javax.swing.JButton();
        btnZonaC9 = new javax.swing.JButton();
        btnZonaC11 = new javax.swing.JButton();
        btnZonaC8 = new javax.swing.JButton();
        btnZonaC10 = new javax.swing.JButton();
        btnZonaC12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnZonaB1 = new javax.swing.JButton();
        btnZonaB2 = new javax.swing.JButton();
        btnZonaB3 = new javax.swing.JButton();
        btnZonaB4 = new javax.swing.JButton();
        btnZonaB5 = new javax.swing.JButton();
        btnZonaB6 = new javax.swing.JButton();
        btnZonaB7 = new javax.swing.JButton();
        btnZonaB8 = new javax.swing.JButton();
        btnZonaB9 = new javax.swing.JButton();
        btnZonaB10 = new javax.swing.JButton();
        btnZonaB11 = new javax.swing.JButton();
        btnZonaB12 = new javax.swing.JButton();
        btnZonaB13 = new javax.swing.JButton();
        btnZonaB14 = new javax.swing.JButton();
        btnZonaB15 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnZonaD = new javax.swing.JButton();
        btnZonaD1 = new javax.swing.JButton();
        btnZonaD2 = new javax.swing.JButton();
        btnZonaD3 = new javax.swing.JButton();
        btnZonaD4 = new javax.swing.JButton();
        btnZonaD5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnZonaA = new javax.swing.JButton();
        btnZonaA1 = new javax.swing.JButton();
        btnZonaA2 = new javax.swing.JButton();
        btnZonaA3 = new javax.swing.JButton();
        btnZonaA4 = new javax.swing.JButton();
        btnZonaA5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxVehiculo = new javax.swing.JComboBox<>();
        cbxSalidaEntrada = new javax.swing.JComboBox<>();
        btnSelccionado = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                              RESIDENCIAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Ocupado");

        lblLIbre.setText("Libre");

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblLIbre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(lblLIbre))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText(" Edificio Ingenierias");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnZonaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC1ActionPerformed(evt);
            }
        });

        btnZonaC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC2ActionPerformed(evt);
            }
        });

        btnZonaC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC3ActionPerformed(evt);
            }
        });

        btnZonaC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC4ActionPerformed(evt);
            }
        });

        btnZonaC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC5ActionPerformed(evt);
            }
        });

        btnZonaC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC6ActionPerformed(evt);
            }
        });

        btnZonaC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC7ActionPerformed(evt);
            }
        });

        btnZonaC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC9ActionPerformed(evt);
            }
        });

        btnZonaC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC11ActionPerformed(evt);
            }
        });

        btnZonaC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC8ActionPerformed(evt);
            }
        });

        btnZonaC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC10ActionPerformed(evt);
            }
        });

        btnZonaC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaC12ActionPerformed(evt);
            }
        });

        jLabel7.setText("Zona C");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnZonaC4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaC5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnZonaC7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaC8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnZonaC10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaC11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZonaC9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZonaC12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZonaC6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnZonaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZonaC3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaC3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaC4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaC8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaC11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaC12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnZonaB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB1ActionPerformed(evt);
            }
        });

        btnZonaB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB2ActionPerformed(evt);
            }
        });

        btnZonaB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB3ActionPerformed(evt);
            }
        });

        btnZonaB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB4ActionPerformed(evt);
            }
        });

        btnZonaB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB5ActionPerformed(evt);
            }
        });

        btnZonaB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB6ActionPerformed(evt);
            }
        });

        btnZonaB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB7ActionPerformed(evt);
            }
        });

        btnZonaB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB8ActionPerformed(evt);
            }
        });

        btnZonaB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB9ActionPerformed(evt);
            }
        });

        btnZonaB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB10ActionPerformed(evt);
            }
        });

        btnZonaB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB11ActionPerformed(evt);
            }
        });

        btnZonaB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB12ActionPerformed(evt);
            }
        });

        btnZonaB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB13ActionPerformed(evt);
            }
        });

        btnZonaB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB14ActionPerformed(evt);
            }
        });

        btnZonaB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaB15ActionPerformed(evt);
            }
        });

        jLabel8.setText("Zona B");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnZonaB4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnZonaB7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnZonaB10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnZonaB13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaB15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnZonaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnZonaB2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnZonaB4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaB7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaB11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaB13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaB15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnZonaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaDActionPerformed(evt);
            }
        });

        btnZonaD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaD1ActionPerformed(evt);
            }
        });

        btnZonaD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaD2ActionPerformed(evt);
            }
        });

        btnZonaD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaD3ActionPerformed(evt);
            }
        });

        btnZonaD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaD4ActionPerformed(evt);
            }
        });

        btnZonaD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaD5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Zona D");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnZonaD3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaD5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaD4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnZonaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaD1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnZonaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnZonaD1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnZonaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaD3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaD5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaD4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnZonaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaAActionPerformed(evt);
            }
        });

        btnZonaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaA1ActionPerformed(evt);
            }
        });

        btnZonaA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaA2ActionPerformed(evt);
            }
        });

        btnZonaA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaA3ActionPerformed(evt);
            }
        });

        btnZonaA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaA4ActionPerformed(evt);
            }
        });

        btnZonaA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaA5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Zona A");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnZonaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnZonaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZonaA2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnZonaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaA5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZonaA4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZonaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZonaA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZonaA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZonaA5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZonaA4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel11.setText("    ZONA DE VEGETACION");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("TIPO DE VEHICULO:");

        jLabel6.setText("ESTADO: ");

        cbxSalidaEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA", "SALIDA" }));

        btnSelccionado.setText("SELECCIONAR");
        btnSelccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSalidaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelccionado)
                        .addGap(38, 38, 38))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxSalidaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelccionado))
                .addGap(29, 29, 29))
        );

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnguardar)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZonaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaAActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA.getBackground().equals(Color.WHITE)) {
                    btnZonaA.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA.getBackground().equals(Color.GREEN)){
                    btnZonaA.setBackground(Color.WHITE);
                    estado=3;    
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
        
    }//GEN-LAST:event_btnZonaAActionPerformed

    private void btnZonaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaA1ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA1.getBackground().equals(Color.WHITE)) {
                    btnZonaA1.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA1.getBackground().equals(Color.GREEN)){
                    btnZonaA1.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
                btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaA1ActionPerformed

    private void btnZonaA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaA2ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA2.getBackground().equals(Color.WHITE)) {
                    btnZonaA2.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA2.getBackground().equals(Color.GREEN)){
                    btnZonaA2.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaA2ActionPerformed

    private void btnZonaA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaA3ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA3.getBackground().equals(Color.WHITE)) {
                    btnZonaA3.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA3.getBackground().equals(Color.GREEN)){
                    btnZonaA3.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
                btnguardar.enable(true);

    }//GEN-LAST:event_btnZonaA3ActionPerformed

    private void btnZonaA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaA4ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA4.getBackground().equals(Color.WHITE)) {
                    btnZonaA4.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA4.getBackground().equals(Color.GREEN)){
                    btnZonaA4.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaA4ActionPerformed

    private void btnZonaA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaA5ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaA5.getBackground().equals(Color.WHITE)) {
                    btnZonaA5.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaA5.getBackground().equals(Color.GREEN)){
                    btnZonaA5.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaA5ActionPerformed

    private void btnZonaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaDActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD.getBackground().equals(Color.WHITE)) {
                    btnZonaD.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD.getBackground().equals(Color.GREEN)){
                    btnZonaD.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaDActionPerformed

    private void btnZonaD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaD1ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD1.getBackground().equals(Color.WHITE)) {
                    btnZonaD1.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD1.getBackground().equals(Color.GREEN)){
                    btnZonaD1.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaD1ActionPerformed

    private void btnZonaD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaD2ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD2.getBackground().equals(Color.WHITE)) {
                    btnZonaD2.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD2.getBackground().equals(Color.GREEN)){
                    btnZonaD2.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaD2ActionPerformed

    private void btnZonaD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaD3ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD3.getBackground().equals(Color.WHITE)) {
                    btnZonaD3.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD3.getBackground().equals(Color.GREEN)){
                    btnZonaD3.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaD3ActionPerformed

    private void btnZonaD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaD5ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD5.getBackground().equals(Color.WHITE)) {
                    btnZonaD5.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD5.getBackground().equals(Color.GREEN)){
                    btnZonaD5.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);

    }//GEN-LAST:event_btnZonaD5ActionPerformed

    private void btnZonaD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaD4ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaD4.getBackground().equals(Color.WHITE)) {
                    btnZonaD4.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaD4.getBackground().equals(Color.GREEN)){
                    btnZonaD4.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaD4ActionPerformed

    private void btnZonaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC1ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC1.getBackground().equals(Color.WHITE)) {
                    btnZonaC1.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC1.getBackground().equals(Color.GREEN)){
                    btnZonaC1.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC1ActionPerformed

    private void btnZonaC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC2ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC2.getBackground().equals(Color.WHITE)) {
                    btnZonaC2.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC2.getBackground().equals(Color.GREEN)){
                    btnZonaC2.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC2ActionPerformed

    private void btnZonaC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC3ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC3.getBackground().equals(Color.WHITE)) {
                    btnZonaC3.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC3.getBackground().equals(Color.GREEN)){
                    btnZonaC3.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC3ActionPerformed

    private void btnZonaC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC4ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC4.getBackground().equals(Color.WHITE)) {
                    btnZonaC4.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC4.getBackground().equals(Color.GREEN)){
                    btnZonaC4.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC4ActionPerformed

    private void btnZonaC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC5ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC5.getBackground().equals(Color.WHITE)) {
                    btnZonaC5.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC5.getBackground().equals(Color.GREEN)){
                    btnZonaC5.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC5ActionPerformed

    private void btnZonaC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC6ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC6.getBackground().equals(Color.WHITE)) {
                    btnZonaC6.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC6.getBackground().equals(Color.GREEN)){
                    btnZonaC6.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC6ActionPerformed

    private void btnZonaC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC7ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC7.getBackground().equals(Color.WHITE)) {
                    btnZonaC7.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC7.getBackground().equals(Color.GREEN)){
                    btnZonaC7.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC7ActionPerformed

    private void btnZonaC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC8ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC8.getBackground().equals(Color.WHITE)) {
                    btnZonaC8.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC8.getBackground().equals(Color.GREEN)){
                    btnZonaC8.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC8ActionPerformed

    private void btnZonaC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC9ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC9.getBackground().equals(Color.WHITE)) {
                    btnZonaC9.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC9.getBackground().equals(Color.GREEN)){
                    btnZonaC9.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC9ActionPerformed

    private void btnZonaC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC10ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC10.getBackground().equals(Color.WHITE)) {
                    btnZonaC10.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC10.getBackground().equals(Color.GREEN)){
                    btnZonaC10.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC10ActionPerformed

    private void btnZonaC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC11ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC11.getBackground().equals(Color.WHITE)) {
                    btnZonaC11.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC11.getBackground().equals(Color.GREEN)){
                    btnZonaC11.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC11ActionPerformed

    private void btnZonaC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaC12ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaC12.getBackground().equals(Color.WHITE)) {
                    btnZonaC12.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaC12.getBackground().equals(Color.GREEN)){
                    btnZonaC12.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaC12ActionPerformed

    private void btnZonaB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB2ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB2.getBackground().equals(Color.WHITE)) {
                    btnZonaB2.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB2.getBackground().equals(Color.GREEN)){
                    btnZonaB2.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB2ActionPerformed

    private void btnZonaB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB1ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB1.getBackground().equals(Color.WHITE)) {
                    btnZonaB1.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB1.getBackground().equals(Color.GREEN)){
                    btnZonaB1.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB1ActionPerformed

    private void btnZonaB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB3ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB3.getBackground().equals(Color.WHITE)) {
                    btnZonaB3.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB3.getBackground().equals(Color.GREEN)){
                    btnZonaB3.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB3ActionPerformed

    private void btnZonaB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB4ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB4.getBackground().equals(Color.WHITE)) {
                    btnZonaB4.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB4.getBackground().equals(Color.GREEN)){
                    btnZonaB4.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB4ActionPerformed

    private void btnZonaB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB5ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB5.getBackground().equals(Color.WHITE)) {
                    btnZonaB5.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB5.getBackground().equals(Color.GREEN)){
                    btnZonaB5.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB5ActionPerformed

    private void btnZonaB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB6ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB6.getBackground().equals(Color.WHITE)) {
                    btnZonaB6.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB6.getBackground().equals(Color.GREEN)){
                    btnZonaB6.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB6ActionPerformed

    private void btnZonaB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB7ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB7.getBackground().equals(Color.WHITE)) {
                    btnZonaB7.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB7.getBackground().equals(Color.GREEN)){
                    btnZonaB7.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB7ActionPerformed

    private void btnZonaB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB8ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB8.getBackground().equals(Color.WHITE)) {
                    btnZonaB8.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB8.getBackground().equals(Color.GREEN)){
                    btnZonaB8.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB8ActionPerformed

    private void btnZonaB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB9ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB9.getBackground().equals(Color.WHITE)) {
                    btnZonaB9.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB9.getBackground().equals(Color.GREEN)){
                    btnZonaB9.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB9ActionPerformed

    private void btnZonaB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB10ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB10.getBackground().equals(Color.WHITE)) {
                    btnZonaB10.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB10.getBackground().equals(Color.GREEN)){
                    btnZonaB10.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB10ActionPerformed

    private void btnZonaB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB11ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB11.getBackground().equals(Color.WHITE)) {
                    btnZonaB11.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB11.getBackground().equals(Color.GREEN)){
                    btnZonaB11.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB11ActionPerformed

    private void btnZonaB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB12ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB12.getBackground().equals(Color.WHITE)) {
                    btnZonaB12.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB12.getBackground().equals(Color.GREEN)){
                    btnZonaB12.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB12ActionPerformed

    private void btnZonaB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB13ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB13.getBackground().equals(Color.WHITE)) {
                    btnZonaB13.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB13.getBackground().equals(Color.GREEN)){
                    btnZonaB13.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB13ActionPerformed

    private void btnZonaB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB14ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB14.getBackground().equals(Color.WHITE)) {
                    btnZonaB14.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB14.getBackground().equals(Color.GREEN)){
                    btnZonaB14.setBackground(Color.WHITE);
                    estado=3;
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB14ActionPerformed

    private void btnZonaB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaB15ActionPerformed
        // TODO add your handling code here:
        if(estado==1){
            if (btnZonaB15.getBackground().equals(Color.WHITE)) {
                    btnZonaB15.setBackground(Color.GREEN);
                    estado=3;
            }    
        
        }
        if(estado == 2){
            if (btnZonaB15.getBackground().equals(Color.GREEN)){
                    btnZonaB15.setBackground(Color.WHITE);
                    estado=3;    
            }
        }
        if(estado == 0 ){
            Utilidades.Utilidades.mensajeAdvertencia("PRIMERO SE DEBE SELECCIONAR SI ES ESTADO SALIDA O ES INGRESO DEL VEHICULO", "ADVERTENCIA");
        }
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnZonaB15ActionPerformed

    private void btnSelccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelccionadoActionPerformed
        // TODO aqui haces la logica para guardar el vehiculo en un lugar
        //usas get como en el que hice para el registro de vehiculos y conductores
        getEstado();
        btnSelccionado.setEnabled(false);
        if(tipoEstado.equals("INGRESO")){
            estado=1;
        }else{
            estado=2;
        }
        
        
    }//GEN-LAST:event_btnSelccionadoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        estado=0;
        btnSelccionado.setEnabled(true);
        btnguardar.setEnabled(false);
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMapaParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMapaParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMapaParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMapaParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMapaParqueadero().setVisible(true);
            }
        });
    }

    public String getEstado(){
        int i;
        if (cbxSalidaEntrada.getSelectedIndex() == 0){
            tipoEstado = "INGRESO";
        }
        if(cbxSalidaEntrada.getSelectedIndex() == 1){
            tipoEstado = "SALIDA";
        }
        return tipoEstado;
    }
    public void setPlacas(String prmPlacas[]){
        int longitud = prmPlacas.length; 
    }
    
    
    @Override
    public void actualizar(AModel amodel) {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelccionado;
    private javax.swing.JButton btnZonaA;
    private javax.swing.JButton btnZonaA1;
    private javax.swing.JButton btnZonaA2;
    private javax.swing.JButton btnZonaA3;
    private javax.swing.JButton btnZonaA4;
    private javax.swing.JButton btnZonaA5;
    private javax.swing.JButton btnZonaB1;
    private javax.swing.JButton btnZonaB10;
    private javax.swing.JButton btnZonaB11;
    private javax.swing.JButton btnZonaB12;
    private javax.swing.JButton btnZonaB13;
    private javax.swing.JButton btnZonaB14;
    private javax.swing.JButton btnZonaB15;
    private javax.swing.JButton btnZonaB2;
    private javax.swing.JButton btnZonaB3;
    private javax.swing.JButton btnZonaB4;
    private javax.swing.JButton btnZonaB5;
    private javax.swing.JButton btnZonaB6;
    private javax.swing.JButton btnZonaB7;
    private javax.swing.JButton btnZonaB8;
    private javax.swing.JButton btnZonaB9;
    private javax.swing.JButton btnZonaC1;
    private javax.swing.JButton btnZonaC10;
    private javax.swing.JButton btnZonaC11;
    private javax.swing.JButton btnZonaC12;
    private javax.swing.JButton btnZonaC2;
    private javax.swing.JButton btnZonaC3;
    private javax.swing.JButton btnZonaC4;
    private javax.swing.JButton btnZonaC5;
    private javax.swing.JButton btnZonaC6;
    private javax.swing.JButton btnZonaC7;
    private javax.swing.JButton btnZonaC8;
    private javax.swing.JButton btnZonaC9;
    private javax.swing.JButton btnZonaD;
    private javax.swing.JButton btnZonaD1;
    private javax.swing.JButton btnZonaD2;
    private javax.swing.JButton btnZonaD3;
    private javax.swing.JButton btnZonaD4;
    private javax.swing.JButton btnZonaD5;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbxSalidaEntrada;
    private javax.swing.JComboBox<String> cbxVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblLIbre;
    // End of variables declaration//GEN-END:variables
}
