/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.Observable;
import java.util.Observer;
import negocio.GestorVehiculo;
import negocio.GestorVehiculoPersona;
import negocio.Persona;
import negocio.Vehiculo;

/**
 *
 * @author JUAN
 */
public class GUIRegistrarVehiculo extends javax.swing.JInternalFrame implements Observer{
    private final GestorVehiculo gestorVehiculo = new GestorVehiculo();
    private String idConductor;
    private String placaVehiculo, marca, tipoVehiculo;
    private final GestorVehiculoPersona gestorUsuario = new GestorVehiculoPersona();

    /**
     * Creates new form GUIRegistrarVehiculo
     */
    public GUIRegistrarVehiculo() {
        initComponents();
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIdConductor = new javax.swing.JLabel();
        txbIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txbPlaca = new javax.swing.JTextField();
        lbllMarca = new javax.swing.JLabel();
        txbMarca = new javax.swing.JTextField();
        lblTipoVehiculo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(12, 61, 135));
        jPanel1.setForeground(new java.awt.Color(12, 61, 135));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unicauca.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.png"))); // NOI18N

        lblIdConductor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdConductor.setForeground(new java.awt.Color(255, 255, 255));
        lblIdConductor.setText("IDENTIDICACION DEL CONDUCTOR: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLACA DEL VEHICULO : ");

        lbllMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllMarca.setForeground(new java.awt.Color(255, 255, 255));
        lbllMarca.setText("MARCA DEL VEHICULO: ");

        lblTipoVehiculo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoVehiculo.setText("TIPO DE VEHICULO : ");

        cbxTipo.setForeground(new java.awt.Color(12, 61, 135));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Motocicleta" }));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(12, 61, 135));
        jButton1.setText("GUARDAR VEHICULO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdConductor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipoVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbllMarca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txbMarca))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txbPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txbIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdConductor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txbPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllMarca)
                    .addComponent(txbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVehiculo)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!validarCampos()){
            String idConductor;
            String placa, marca, tipoVehiculo, confirmacion;
            placa = getPlaca();
            marca = getMarca();
            tipoVehiculo = getTipoVehiculo();
            idConductor = getIdConductor();
            Persona conductor = gestorUsuario.BuscarPersona(Integer.parseInt(idConductor));
            if(conductor == null){
                Utilidades.Utilidades.mensajeError("ERROR", "El conductor no se encuentra registrado");
            }else{
                Vehiculo objVehiculo = new Vehiculo(idConductor, placa, marca, tipoVehiculo);
                confirmacion = gestorVehiculo.registrarVehiculo(objVehiculo);
                Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean validarCampos(){
        if(txbIdentificacion.getText().isEmpty() || txbPlaca.getText().isEmpty() || txbMarca.getText().isEmpty()){
            Utilidades.Utilidades.mensajeError("FALTA LLENAR CAMPOS PARA PODER HACER EL REGISTRO EXITOSO", "CAMPOS NULOS");
            return true;
        }
        return false;
    }
    public String getIdConductor(){
        idConductor = txbIdentificacion.getText();
        return idConductor;
    }
    public String getPlaca(){
        placaVehiculo = txbPlaca.getText();
        return placaVehiculo;
    }
    public String getMarca(){
        marca = txbMarca.getText();
        return marca;
    }
    public String getTipoVehiculo(){
        int i;
        if (cbxTipo.getSelectedIndex() == 0){
            tipoVehiculo = "Automovil";
        }
        if(cbxTipo.getSelectedIndex() == 1){
            tipoVehiculo = "Motocicleta";
        }
        return tipoVehiculo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdConductor;
    private javax.swing.JLabel lblTipoVehiculo;
    private javax.swing.JLabel lbllMarca;
    private javax.swing.JTextField txbIdentificacion;
    private javax.swing.JTextField txbMarca;
    private javax.swing.JTextField txbPlaca;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
