/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Utilidades.Utilidades;
import negocio.GestorConductor;
import negocio.GestorVehiculoPersona;
import negocio.GestorVigilante;
import negocio.Persona;
import negocio.Vigilante;

/**
 *
 * @author JUAN
 */
public class GUIRegistrarVigilante extends javax.swing.JInternalFrame {
    private String identificacion, nombre, apellido, genero, fechaNacimiento, rol ,usuario,contrasenia,empresa;
   private final GestorVigilante gestorVigilante = new GestorVigilante();
   private final GestorVehiculoPersona gestorUsuario = new GestorVehiculoPersona();
   
    /**
     * Creates new form GUIRegistrarVigilante
     */
    public GUIRegistrarVigilante() {
        
        initComponents();
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbMujer = new javax.swing.JRadioButton();
        jcMes = new com.toedter.calendar.JMonthChooser();
        jcDia = new com.toedter.components.JSpinField();
        jLabel1 = new javax.swing.JLabel();
        lblApellidoVigilante = new javax.swing.JLabel();
        txbNombreVigilante = new javax.swing.JTextField();
        jcAño = new com.toedter.calendar.JYearChooser();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblgenero = new javax.swing.JLabel();
        lblnombreVigilante = new javax.swing.JLabel();
        txtnapellidoVigilante = new javax.swing.JTextField();
        rbHombre = new javax.swing.JRadioButton();
        txbCedulal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblUsuario = new java.awt.Label();
        txtUsuario = new javax.swing.JTextField();
        btnVerificar = new java.awt.Button();
        lblContraseña = new java.awt.Label();
        txtContraseña = new javax.swing.JTextField();
        lblEmpresa = new java.awt.Label();
        txtEmpresa = new javax.swing.JTextField();

        setBackground(new java.awt.Color(12, 61, 135));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(12, 61, 135));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEDULA:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unicauca.png"))); // NOI18N

        rbMujer.setBackground(new java.awt.Color(12, 61, 135));
        rbMujer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbMujer.setForeground(new java.awt.Color(255, 255, 255));
        rbMujer.setText("MUJER");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.png"))); // NOI18N

        lblApellidoVigilante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApellidoVigilante.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoVigilante.setText("APELLIDOS DEL VIGILANTE :");

        jcAño.setValue(2000);

        lblFechaNacimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("FECHA DE NACIMIENTO :");

        lblgenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblgenero.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero.setText("GENERO : ");

        lblnombreVigilante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblnombreVigilante.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreVigilante.setText("NOMBRES DEL VIGILANTE :");

        rbHombre.setBackground(new java.awt.Color(12, 61, 135));
        rbHombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbHombre.setForeground(new java.awt.Color(255, 255, 255));
        rbHombre.setText("HOMBRE");

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setForeground(new java.awt.Color(12, 61, 135));
        btnGuardar.setText("GUARDAR INFORMACION DEL VIGILANTE");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText(" USUARIO :");

        btnVerificar.setActionCommand("Verificar");
        btnVerificar.setLabel("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setName(""); // NOI18N
        lblContraseña.setText("CONTRASEÑA :");

        lblEmpresa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresa.setText("EMPRESA QUE PERTENECE :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblgenero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbHombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbMujer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFechaNacimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txbCedulal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblApellidoVigilante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnapellidoVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblnombreVigilante)
                                        .addGap(18, 18, 18)
                                        .addComponent(txbNombreVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txbCedulal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbNombreVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombreVigilante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoVigilante)
                    .addComponent(txtnapellidoVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgenero)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNacimiento)
                            .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!validarCampo()){
            String respuesta;
            String confirmacion;
            String id = getIdentificacion();
            String nombre = getNombre();
            String apellido = getApellido(); 
            String genero = getGenero();
            String usuario = getUsuario();
            String contrasenia = getContrasenia();
            String empresa = getEmpresa();
            String fechaNacimiento = getFechaNacimiento();
            String rol = getRol();
            Vigilante objVigilante;
            Persona  objpersona = gestorUsuario.BuscarPersona(Integer.parseInt(id));
            if (objpersona == null){

                objVigilante = new Vigilante(id, nombre, apellido, genero, fechaNacimiento,empresa,usuario,contrasenia);

                confirmacion = gestorVigilante.registrarVigilante(objVigilante);
                Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");
                limpiar();
            }else{
                Utilidades.mensajeError("El Vigilante con esa identificación ya se encuentra registrado.", "Advertencia");
                limpiar();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        
        if(!(txtUsuario.getText().isEmpty())){
            String esta = gestorUsuario.BuscarLogin(usuario);
            if (esta == null){
                //confirmacion = gestorConductor.registrarVigilante(objVigilante);
                Utilidades.mensajeExito("El usuario esta diponible!!", "usuario Disponible.");
                btnVerificar.setEnabled(false);
                txtUsuario.setEnabled(false);
                btnGuardar.setEnabled(true);
            }else{
                Utilidades.mensajeError("El Vigilante con esa identificación ya se encuentra registrado.", "Advertencia");
            }
        }else{
            Utilidades.mensajeError("EL USER DEL USUARIO NO PUEDE SER NULO", "CAMPOS NULO");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private java.awt.Button btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JYearChooser jcAño;
    private com.toedter.components.JSpinField jcDia;
    private com.toedter.calendar.JMonthChooser jcMes;
    private javax.swing.JLabel lblApellidoVigilante;
    private java.awt.Label lblContraseña;
    private java.awt.Label lblEmpresa;
    private javax.swing.JLabel lblFechaNacimiento;
    private java.awt.Label lblUsuario;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JLabel lblnombreVigilante;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTextField txbCedulal;
    private javax.swing.JTextField txbNombreVigilante;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtnapellidoVigilante;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampo(){
        if(txbCedulal.getText().isEmpty() || txbNombreVigilante.getText().isEmpty() || 
                txtnapellidoVigilante.getText().isEmpty() || txtEmpresa.getText().isEmpty()
                || validaRadioButon() || txtContraseña.getText().isEmpty()
                || txtUsuario.getText().isEmpty()){
            Utilidades.mensajeError("FALTA LLENAR CAMPOS PARA PODER HACER EL REGISTRO EXITOSO", "CAMPOS NULOS");
            return true;
        }else{
            return false;
        }
    }
    private String getIdentificacion() {
         identificacion=txbCedulal.getText();
        return  identificacion;
    }

    private String getNombre() {
         nombre=txbNombreVigilante.getText();
         return nombre;
    }

    private String getApellido() {
        apellido = txtnapellidoVigilante.getText();
        return apellido;
    }

    private String getGenero() {
           if (rbMujer.isSelected()){
            genero="Femenino";
            }
            if (rbHombre.isSelected()){
                genero= "Masculino";
            }
        return genero;
    }

    private String getFechaNacimiento() {
        int dia = jcDia.getValue();
        int mes = jcMes.getMonth();
        int año = jcAño.getYear();
        fechaNacimiento = dia+ " / "+mes+" / "+año;
        System.out.println(fechaNacimiento);
        return fechaNacimiento;
 
    }
    public boolean validaRadioButon() {
        boolean band = true;
        if (rbHombre.isSelected() == false && rbMujer.isSelected() == false) {
            band = false;
        }
        return band;
    }
    private String getRol() {
    
        rol=  "VIGILANTE";
        return rol;
    }

    private String getUsuario() {
    
         usuario=txtUsuario.getText();
         return usuario;
    }

    private String getContrasenia() {
        contrasenia = txtContraseña.getText();
        return contrasenia;
    }

    private String getEmpresa() {
        empresa = txtEmpresa.getText();
        return empresa;
    }
    private void limpiar(){
        txbCedulal.setText("");
        txbNombreVigilante.setText("");
        txtnapellidoVigilante.setText("");
        txtEmpresa.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        btnGuardar.setEnabled(false);
        btnVerificar.setEnabled(true);
        txtUsuario.setEnabled(true);
    }
}
