/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;
import mvcf.AModel;
import mvcf.AView;
import negocio.GestorConductor;
import negocio.GestorVehiculoPersona;
import negocio.Persona;

/**
 *
 * @author JUAN
 */
public class GUIRegistrarDatosConductor extends javax.swing.JInternalFrame implements AView {
    private String identificacion, nombre, apellido, genero, fechaNacimiento, rol;
   private final GestorConductor gestorConductor = new GestorConductor();
   private final GestorVehiculoPersona gestorUsuario = new GestorVehiculoPersona();
    /**
     * Creates new form GUIRegistrarDatosConductor
     */
    public GUIRegistrarDatosConductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnombreConductor = new javax.swing.JLabel();
        lblApellidoConductor = new javax.swing.JLabel();
        lblgenero = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txbNombreConductor = new javax.swing.JTextField();
        tbxapellidoConductor = new javax.swing.JTextField();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        cbxRol = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txbCedulal = new javax.swing.JTextField();
        jcDia = new com.toedter.components.JSpinField();
        jcMes = new com.toedter.calendar.JMonthChooser();
        jcAño = new com.toedter.calendar.JYearChooser();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(12, 61, 135));

        lblnombreConductor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblnombreConductor.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreConductor.setText("NOMBRES DEL CONDUCTOR :");

        lblApellidoConductor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApellidoConductor.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoConductor.setText("APELLIDOS DEL CONDUCTOR :");

        lblgenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblgenero.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero.setText("GENERO : ");

        lblFechaNacimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("FECHA DE NACIMIENTO :");

        lblRol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setText("ROL :");

        rbHombre.setBackground(new java.awt.Color(12, 61, 135));
        rbHombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbHombre.setForeground(new java.awt.Color(255, 255, 255));
        rbHombre.setText("HOMBRE");

        rbMujer.setBackground(new java.awt.Color(12, 61, 135));
        rbMujer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbMujer.setForeground(new java.awt.Color(255, 255, 255));
        rbMujer.setText("MUJER");

        cbxRol.setForeground(new java.awt.Color(12, 61, 135));
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "DONCENTE", "ESTUDIANTE Y DOCENTE", "ADMINISTRATIVO" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unicauca.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.png"))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setForeground(new java.awt.Color(12, 61, 135));
        btnGuardar.setText("GUARDAR INFORMACION DEL CONDUCTOR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEDULA:");

        jcAño.setEndYear(2003);
        jcAño.setValue(2000);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txbCedulal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblApellidoConductor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbxapellidoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnombreConductor)
                                .addGap(18, 18, 18)
                                .addComponent(txbNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblRol)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblgenero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbHombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbMujer))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblFechaNacimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txbCedulal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombreConductor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoConductor)
                    .addComponent(tbxapellidoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgenero)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!camposNulos()){
            String respuesta;
            String confirmacion;
            String id = getIdentificacion();
            String nombre = getNombre();
            String apellido = getApellido();
            String genero = getGenero();
            String fechaNacimiento = getFechaNacimiento();
            String rol = getRol();
            Persona conductor = gestorUsuario.BuscarPersona(Integer.parseInt(id));
            if (conductor == null){
                conductor = new Persona(id, nombre, apellido, genero, fechaNacimiento, rol);
                confirmacion = gestorConductor.registrarConductor(conductor);
                Utilidades.Utilidades.mensajeExito(confirmacion, "Registro Exitoso.");

            }else{
                Utilidades.Utilidades.mensajeError("El Conductor con esa identificación ya se encuentra registrado.", "Advertencia");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JYearChooser jcAño;
    private com.toedter.components.JSpinField jcDia;
    private com.toedter.calendar.JMonthChooser jcMes;
    private javax.swing.JLabel lblApellidoConductor;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JLabel lblnombreConductor;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTextField tbxapellidoConductor;
    private javax.swing.JTextField txbCedulal;
    private javax.swing.JTextField txbNombreConductor;
    // End of variables declaration//GEN-END:variables
    public String getIdentificacion(){
        identificacion = txbCedulal.getText();
        return identificacion;
    }
    public String getNombre(){
        nombre = txbNombreConductor.getText();
        return nombre;
    }
    public String getApellido(){
        apellido = tbxapellidoConductor.getText();
        return apellido;
    }
    public String getGenero(){
        if (rbMujer.isSelected()){
            genero = "Femenino";
        }else
        if (rbHombre.isSelected()){
            genero = "Masculino";
        }else{
            genero = "";
        }
        return genero;
    }
    
    public String getFechaNacimiento(){
        int dia = jcDia.getValue();
        int mes = jcMes.getMonth();
        int año = jcAño.getYear();
        fechaNacimiento = dia+ " / "+mes+" / "+año;
        System.out.println(fechaNacimiento);
        return fechaNacimiento;
    }
    public String getRol(){
        String rol = (String) cbxRol.getSelectedItem();
        System.out.println(rol);
        return rol;
    }

    @Override
    public void actualizar(AModel amodel) {
    
    }
    public boolean camposNulos (){
        
        if(txbNombreConductor.getText().isEmpty() || txbNombreConductor.getText().isEmpty() || 
                tbxapellidoConductor.getText().isEmpty() || getGenero().equals("")){
            Utilidades.Utilidades.mensajeError("FALTA LLENAR CAMPOS PARA PODER HACER EL REGISTRO EXITOSO", "CAMPOS NULOS");
            return true;
        }
        return false;
    }
}
